# Generated by Django 5.2.7 on 2025-10-28 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('conclusion_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('slug', models.SlugField(unique=True)),
                ('trainig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.training', verbose_name='Treinamento')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['name'],
            },
        ),
    ]
