# Generated by Django 5.2.7 on 2025-10-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
