# Generated by Django 5.2.7 on 2025-10-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='trainig',
            new_name='training',
        ),
    ]
