"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# OUR FOLDER TO SAVE STATICFILES
DATA_DIR = BASE_DIR.parent / 'data' / 'web'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vzyja75v3w@bjd^gh6d8%u-n&obdfz1wdokr)a1r#dg@u!u5-d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # THIRD APPS
    'rest_framework',
    'drf_spectacular',
    'debug_toolbar',
    'axes',

    # MY APPS
    'course',
    'registration',
    'resources',
    'student.apps.StudentConfig',
    'training',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # DJANGO TOOLBAR
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # DJANGO AXES
    'axes.middleware.AxesMiddleware'
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# THIS IS THE BASIC URL OF STATIC
STATIC_URL = 'static/'
# HERE IS THE FOLDER WHERE THE FILES WILL BE SAVED WHEN WE MAKE A "COLLECSTATIC"
STATIC_ROOT = DATA_DIR / 'static'
STATICFILES_DIRS = (
    BASE_DIR / 'templates' / 'static',
)

# THIS IS THE BASIC URL OF STATIC
MEDIA_URL = 'media/'
# HERE IS THE FOLDER WHERE THE FILES WILL BE SAVED WHEN WE MAKE A "COLLECSTATIC"
MEDIA_ROOT = DATA_DIR / 'media'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SETTINGS OF DJANGO-PHONENUMBER-FIELD

PHONENUMBER_DEFAULT_REGION = 'BR'
PHONENUMBER_DEFAULT_FORMAT = 'NATIONAL'


# SETTINGS OF DJANGO TOOLBAR
INTERNAL_IPS = [
    "127.0.0.1",
]

# SETTINGS OF DJANGO AXES
AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_LOCKOUT_PARAMETROS = ['ip_address', ['username', 'user_agent']]
AXES_RESET_ON_SUCCESS = True   # Reinicia o contador após login bem-sucedido

# SETTINGS OF AXES
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# SETTINGS OF DRF-SPECTACULAR
REST_FRAMEWORK = {
    # Informa ao DRF para usar o 'drf-spectacular' para gerar o esquema
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}