# Generated by Django 5.2.7 on 2025-10-28 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_registrations', to='course.course', verbose_name='Turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_registrations', to='course.course', verbose_name='Aluno')),
            ],
        ),
    ]
