# Generated by Django 5.2.7 on 2025-10-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['student'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_registrations', to='student.student', verbose_name='Aluno'),
        ),
    ]
