# Generated by Django 5.2.7 on 2025-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_options_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='e_mail',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
