# Generated by Django 5.2.7 on 2025-10-28 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Descrição')),
                ('type_resource', models.CharField(choices=[('V', 'VÍDEO'), ('P', 'PDF'), ('Z', 'ZIP')], max_length=1)),
                ('previous_acess', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('draft', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['name'],
            },
        ),
    ]
