# Generated by Django 5.2.7 on 2025-10-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='draft',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Rascunho'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='previous_acess',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Acesso prévio'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type_resource',
            field=models.CharField(choices=[('V', 'VÍDEO'), ('P', 'PDF'), ('Z', 'ZIP')], max_length=1, verbose_name='Tipo de recurso'),
        ),
    ]
